services:
  redoc:
    image: redocly/redoc
    container_name: redoc
    restart: unless-stopped
    environment:
      SPEC_URL: "https://omlpi-api.appcivico.com/openapi.yaml"
    ports:
      - "172.17.0.1:2004:80"

  db:
    image: postgres:16
    restart: unless-stopped
    container_name: omlpi_pg_db
    hostname: db
    environment:
      POSTGRES_USER: "${POSTGRESQL_USER}"
      POSTGRES_DB: "${POSTGRESQL_DBNAME}"
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
    volumes:
      - ${DATA_PATH}/omlpi_pg_db:/var/lib/postgresql/data
    networks:
      - omlpi_network

  strapi_db:
    image: postgres:16
    restart: unless-stopped
    container_name: strapi_pg_db
    hostname: strapi_db
    environment:
      POSTGRES_USER: "${STRAPI_POSTGRESQL_USER}"
      POSTGRES_DB: "${STRAPI_POSTGRESQL_DBNAME}"
      POSTGRES_PASSWORD: "${STRAPI_POSTGRESQL_PASSWORD}"
    volumes:
      - ${DATA_PATH}/strapi_pg_db:/var/lib/postgresql/data
    networks:
      - omlpi_network

  strapi:
    image: strapi/strapi:3.3.3-node14
    container_name: omlpi_strapi
    restart: unless-stopped
    environment:
      ADMIN_JWT_SECRET: "${ADMIN_JWT_SECRET}"
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi_db
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "${STRAPI_POSTGRESQL_USER}"
      DATABASE_NAME: "${STRAPI_POSTGRESQL_DBNAME}"
      DATABASE_PASSWORD: "${STRAPI_POSTGRESQL_PASSWORD}"
    volumes:
      - ${STRAPI_SRC}:/srv/app/
    ports:
      - "172.17.0.1:2001:1337"
    networks:
      - omlpi_network

  cms_search:
    container_name: cms_search
    build:
      context: ./omlpi-cms-search
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "172.17.0.1:2003:1337"
    environment:
      DATABASE_URL: "postgresql://$POSTGRESQL_USER:$POSTGRESQL_PASSWORD@db:5432/$POSTGRESQL_DBNAME"

    networks:
      - omlpi_network

    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: 100MB

  api:
    container_name: omlpi_api
    # ver build-container.sh e README.md
    image: appcivico/omlpi_api
    restart: unless-stopped
    ports:
      - "172.17.0.1:2002:8080"
    volumes:
      # mantém o container atualizado com o código fonte, como se fosse PHP
      - ./omlpi-api:/src
      - ${DATA_PATH}/api_logs:/data
    environment:
      API_PORT: "8080"
      API_WORKERS: "3"
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: "${POSTGRESQL_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_DBNAME: "${POSTGRESQL_DBNAME}"

    networks:
      - omlpi_network

    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: 100MB

  www:
    container_name: www
    build:
      context: ./omlpi-www
      dockerfile: Dockerfile
    networks:
      - omlpi_network
    restart: unless-stopped
    ports:
      - "${BIND_INTERFACE}:${SMAE_WWW_LISTEN}:80"
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: 1MB

networks:
  omlpi_network:
    driver: bridge
